name: "Podcast Generator"
author: "Illia"
description: "Generate a feed for a podcast"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "gir-branch"
  color: "red"
inputs:
  email:
    description: The commiter's email address
    reqiered: true
    default: ${{ github.actor }}@localhost
  name:
    description: The commiter's name
    required: true
    default: ${{ github.actor }}